workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        XCODE_VERSION: 15.4  # Choose latest
      ios_signing:
        distribution_type: development  # Or app_store for release
        bundle_id: com.crazyp.TrueNASAdmin
    scripts:
      - name: Build iOS app
        script: xcodebuild build -project TrueNASAdmin.xcodeproj -scheme TrueNASAdmin -sdk iphoneos -configuration Release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - crazyp@icloud.com
