name: TrueNASAdmin
options:
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  deploymentTarget:
    iOS: 17.0
configs:
  Debug: debug
  Release: release
packages: {}
schemes:
  TrueNASAdmin:
    build:
      targets:
        TrueNASAdmin: all
    test:
      targets:
        TrueNASAdminTests: [test]
targets:
  TrueNASAdmin:
    type: application
    platform: iOS
    sources:
      - path: Sources
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.TrueNASAdmin
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        SWIFT_VERSION: 5.0
  TrueNASAdminTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: TrueNASAdmin
